name: chat_flutter
description: A new Flutter application.
version: 1.0.0+1
environment:
    sdk: '>=2.1.0 <3.0.0'
dependencies:
    flutter:
        sdk: flutter
    cupertino_icons:            ^0.1.2
    cloud_firestore:            0.12.11
    image_picker:               0.6.2+2
    google_sign_in:             4.0.14
    firebase_storage:           3.0.10
    firebase_auth:              0.15.1
    provider:                   3.2.0
    flutter_launcher_icons:     0.7.4
dev_dependencies:
    flutter_test:
        sdk: flutter
flutter:
    uses-material-design: true
    assets:
        - assets/images/logo.jpg
        - assets/images/topPlayStore.png
        - assets/images/white_background.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
      
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
      
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
      
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  #https://pub.dev/packages/flutter_launcher_icons
flutter_icons:
  image_path: "assets/images/logo.jpg"
  android: true
  ios: true
  image_path_android: "assets/images/logo.jpg"
  image_path_ios: "assets/images/logo.jpg"
  adaptive_icon_foreground: "assets/images/logo.jpg"
  adaptive_icon_background: "assets/images/white_background.png"  